services:
  db:
    image: postgres:17-alpine
    container_name: premier_bank_db
    environment:
      POSTGRES_DB: premier_bank
      POSTGRES_USER: premier
      POSTGRES_PASSWORD: premier123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U premier -d premier_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
